### ISSUE TITLE
SEVG on Apple silicon macOS

### ISSUE THREAD

**Issue by Watson1978** [ffi/ffi#800] opened 2020-07-08 14:50 UTC
I tried sample code in README on Apple silicon macOS, it causes SEGV.

```
$ ruby -v
ruby 2.8.0dev (2020-07-08T14:27:10Z master 9fc25811d5) [arm64-darwin20]

$ gem i ffi
Fetching ffi-1.13.1.gem
Building native extensions. This could take a while...
Successfully installed ffi-1.13.1
1 gem installed


$ ruby ffi.rb
/Users/watson/.rbenv/versions/2.8.0/lib/ruby/gems/2.8.0/gems/ffi-1.13.1/lib/ffi/library.rb:275: [BUG] Bus Error at 0x0000000103460000
ruby 2.8.0dev (2020-07-08T14:27:10Z master 9fc25811d5) [arm64-darwin20]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0005 p:---- s:0035 e:000034 CFUNC  :attach
c:0004 p:0250 s:0029 e:000028 METHOD /Users/watson/.rbenv/versions/2.8.0/lib/ruby/gems/2.8.0/gems/ffi-1.13.1/lib/ffi/library.rb:275
c:0003 p:0032 s:0009 e:000008 CLASS  ffi.rb:6
c:0002 p:0013 s:0006 e:000005 EVAL   ffi.rb:3 [FINISH]
c:0001 p:0000 s:0003 E:0021f0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
ffi.rb:3:in `<main>'
ffi.rb:6:in `<module:MyLib>'
/Users/watson/.rbenv/versions/2.8.0/lib/ruby/gems/2.8.0/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach_function'
/Users/watson/.rbenv/versions/2.8.0/lib/ruby/gems/2.8.0/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach'

-- Other runtime information -----------------------------------------------

... snip ...
```

Full crash log is in https://gist.github.com/Watson1978/85f1b5ff076a2d3e36057af0ab854299

### Test code
```
require 'ffi'

module MyLib
  extend FFI::Library
  ffi_lib 'c'
  attach_function :puts, [ :string ], :int
end

MyLib.puts 'Hello, World using libc!'
```

**Comment by Watson1978** [comment] 2020-07-08 15:03
Currently, the memory area which is used in `ffi_prep_closure_loc()` has allocated by `mmap()`.
Apparently, it crashes on ARM cpu.

Seems that we can avoid the crash by using `ffi_closure_alloc` as follows. (it is incomplete patch)

```diff
diff --git a/ext/ffi_c/ClosurePool.c b/ext/ffi_c/ClosurePool.c
index 45411b4..7b90a47 100644
--- a/ext/ffi_c/ClosurePool.c
+++ b/ext/ffi_c/ClosurePool.c
@@ -144,6 +144,7 @@ rbffi_Closure_Alloc(ClosurePool* pool)
     int nclosures;
     long trampolineSize;
     int i;
+    ffi_closure *pcl;
 
     if (pool->list != NULL) {
         Closure* closure = pool->list;
@@ -157,18 +158,19 @@ rbffi_Closure_Alloc(ClosurePool* pool)
     nclosures = (int) (pageSize / trampolineSize);
     block = calloc(1, sizeof(*block));
     list = calloc(nclosures, sizeof(*list));
-    code = allocatePage();
 
-    if (block == NULL || list == NULL || code == NULL) {
-        snprintf(errmsg, sizeof(errmsg), "failed to allocate a page. errno=%d (%s)", errno, strerror(errno));
-        goto error;
-    }
+    /* if (block == NULL || list == NULL || code == NULL) { */
+    /*     snprintf(errmsg, sizeof(errmsg), "failed to allocate a page. errno=%d (%s)", errno, strerror(errno)); */
+    /*     goto error; */
+    /* } */
 
     for (i = 0; i < nclosures; ++i) {
         Closure* closure = &list[i];
         closure->next = &list[i + 1];
         closure->pool = pool;
-        closure->code = ((char *)code + (i * trampolineSize));
+        pcl = ffi_closure_alloc(trampolineSize, &code);
+        closure->pcl = pcl;
+        closure->code = code;
 
         if (!(*pool->prep)(pool->ctx, closure->code, closure, errmsg, sizeof(errmsg))) {
             goto error;
@@ -257,7 +259,9 @@ freePage(void *addr)
 #if !defined(__CYGWIN__) && (defined(_WIN32) || defined(__WIN32__))
     return VirtualFree(addr, 0, MEM_RELEASE);
 #else
-    return munmap(addr, pageSize) == 0;
+    ffi_closure_free(addr);
+    return TRUE;
+    //return munmap(addr, pageSize) == 0;
 #endif
 }
 
@@ -268,7 +272,7 @@ protectPage(void* page)
     DWORD oldProtect;
     return VirtualProtect(page, pageSize, PAGE_EXECUTE_READ, &oldProtect);
 #else
-    return mprotect(page, pageSize, PROT_READ | PROT_EXEC) == 0;
+    return TRUE; //mprotect(page, pageSize, PROT_READ | PROT_EXEC) == 0;
 #endif
 }
 
diff --git a/ext/ffi_c/ClosurePool.h b/ext/ffi_c/ClosurePool.h
index b842375..c2eb5ca 100644
--- a/ext/ffi_c/ClosurePool.h
+++ b/ext/ffi_c/ClosurePool.h
@@ -36,6 +36,8 @@ struct Closure_ {
     void* info;      /* opaque handle for storing closure-instance specific data */
     void* function;  /* closure-instance specific function, called by custom trampoline */
     void* code;      /* The native trampoline code location */
+    ffi_closure *pcl;
+
     struct ClosurePool_* pool;
     Closure* next;
 };
diff --git a/ext/ffi_c/MethodHandle.c b/ext/ffi_c/MethodHandle.c
index 4dc85fb..bdd5632 100644
--- a/ext/ffi_c/MethodHandle.c
+++ b/ext/ffi_c/MethodHandle.c
@@ -140,7 +140,7 @@ prep_trampoline(void* ctx, void* code, Closure* closure, char* errmsg, size_t er
 #if defined(USE_RAW)
     ffiStatus = ffi_prep_raw_closure(code, &mh_cif, attached_method_invoke, closure);
 #else
-    ffiStatus = ffi_prep_closure_loc(code, &mh_cif, attached_method_invoke, closure, code);
+    ffiStatus = ffi_prep_closure_loc(closure->pcl, &mh_cif, attached_method_invoke, closure, code);
 #endif
     if (ffiStatus != FFI_OK) {
         snprintf(errmsg, errmsgsize, "ffi_prep_closure_loc failed.  status=%#x", ffiStatus);

```

**Comment by larskanis** [comment] 2020-07-08 20:00
We switched to `ffi_closure_alloc()` in the past, but it was quickly reverted in commit 94441aa5f8b694b62f70528011b32c5db3d42dd4 because of issues with `fork()`. See the commit message for more details.

**Comment by Watson1978** [comment] 2020-07-10 16:29
Thank you for the valuable information.

I think it needs memory space that conforms to `ptrauth_strip()`.
I guess that this issue is caused because `mmap()` doesn't provide it.

```c
#ifdef HAVE_PTRAUTH
  codeloc = ptrauth_strip (codeloc, ptrauth_key_asia);
#endif
```

https://github.com/libffi/libffi/blob/45875da4bc71578f6f45471141c14e1743239b7e/src/aarch64/ffi.c#L795-L797

And I think this function might be provided on the Apple platform.
https://opensource.apple.com/source/xnu/xnu-4903.241.1/EXTERNAL_HEADERS/ptrauth.h.auto.html

I will try to find a better way how to switch the allocator on the Apple platform only.

**Comment by Watson1978** [comment] 2020-07-29 13:19
Seems that the implementation of `ffi_prep_closure_loc` is much different for Intel and ARM platform.

For Intel Mac, https://github.com/libffi/libffi/blob/45875da4bc71578f6f45471141c14e1743239b7e/src/x86/ffi64.c#L725
The trampoline code and function which we want to invoke through libffi are assigned in sequential memory area.

For ARM Mac, https://github.com/libffi/libffi/blob/45875da4bc71578f6f45471141c14e1743239b7e/src/aarch64/ffi.c#L777
The most surprising thing for me that it runs the following code

```
  void **config = (void **)((uint8_t *)codeloc - PAGE_MAX_SIZE);
  config[0] = closure;
  config[1] = start;
```

Obviously, it uses non-continuous memory.
(`codeloc` has a head of address which allocated by `mmap` if we used it)

When allocating a memory using `mmap`, we must add `PAGE_MAX_SIZE` region, at least.
Otherwise, it will access the unallocated space and crash.

**Comment by tduehr** [comment] 2020-08-19 15:21
I thought we were testing against ARM builds. Why doesn't this cause issues in the existing `armhf` test suite?

**Comment by Watson1978** [comment] 2020-08-19 15:37
First, this gem works very well on Linux on ARM CPUs.

I'm guessing it's because there are aspects of Linux that are different in manners, as Apple has prepared a text called [ARM64 Function Calling Conventions](https://developer.apple.com/library/archive/documentation/Xcode/Conceptual/iPhoneOSABIReference/Articles/ARM64FunctionCallingConventions.html)

**Comment by lawrence-danna-apple** [comment] 2020-10-02 18:39
There was a [similar issue with cffi](https://foss.heptapod.net/pypy/cffi/-/issues/464)

You should use `ffi_closure_alloc`, as you say, it's not just mapping RWX memory on arm64 mac os.     `codeloc` will actually point to a file-backed mapping of `/usr/lib/libffi-trampolines.dylib`.    There's only RX and RW memory involved, no RWX.

**Comment by larskanis** [comment] 2020-12-19 07:30
Compatibility to arm64-darwin is fixed in ffi-1.14.0. We currently enable `ffi_closure_alloc` only on arm64 by default, but it's possible to manually en-/disable it per `--enable-libffi-alloc` on other operating systems.

**Closed by larskanis** 2020-12-19 07:30 UTC

**Comment by larskanis** [comment] 2020-12-19 07:37
Thank you @Watson1978 for you contributions!

**Comment by klaygomes** [comment] 2021-07-22 23:08
Same problem with version `1.15.3`

-- Control frame information -----------------------------------------------
c:0005 p:---- s:0035 e:000034 CFUNC  :attach
c:0004 p:0258 s:0029 e:000028 METHOD /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275
c:0003 p:0031 s:0009 e:000008 CLASS  ffi.rb:6
c:0002 p:0014 s:0006 e:000005 EVAL   ffi.rb:3 [FINISH]
c:0001 p:0000 s:0003 E:002580 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
ffi.rb:3:in `<main>'
ffi.rb:6:in `<module:MyLib>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275:in `attach_function'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275:in `attach'

-- Other runtime information -----------------------------------------------

**Comment by nevil** [comment] 2022-01-07 09:15
> Same problem with version `1.15.3`
> 
> -- Control frame information ----------------------------------------------- c:0005 p:---- s:0035 e:000034 CFUNC :attach c:0004 p:0258 s:0029 e:000028 METHOD /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.3/lib/ffi/library.rb:275 c:0003 p:0031 s:0009 e:000008 CLASS ffi.rb:6 c:0002 p:0014 s:0006 e:000005 EVAL ffi.rb:3 [FINISH] c:0001 p:0000 s:0003 E:002580 (none) [FINISH]
> 


@klaygomes 
I believe that crash is partly because of the Apple bundled ruby version...
ffi's configuration script expects `RbConfig::CONFIG['host']` to contain "arm" to enable the arm64 compatible code but Apple's ruby  version has it hard coded to `x86_64-apple-darwin21`.
(/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin21/rbconfig.rb)

https://github.com/ffi/ffi/blob/master/ext/ffi_c/extconf.rb#L63

I guess one way to make the configure script detect the correct target architecture would be to invoke "uname -m" and base the configuration on its output...

**Comment by larskanis** [comment] 2022-01-09 14:31
@nevil 
> I believe that crash is partly because of the Apple bundled ruby version...
> ffi's configuration script expects `RbConfig::CONFIG['host']` to contain "arm" to enable the arm64 compatible code but Apple's ruby version has it hard coded to `x86_64-apple-darwin21`.

If this is the problem, the crash should be fixed by switching the libffi allocation method manually by the following workaround:
```sh
gem uninstall ffi
gem install ffi --enable-libffi-alloc
```
or
```sh
gem uninstall ffi
bundle config build.ffi --enable-libffi-alloc
bundle install
```

**Comment by nevil** [comment] 2022-01-10 00:44
@larskanis 

Thanks for your reply!

Yes, I can confirm that `gem install ffi --enable-libffi-alloc` works.

**Comment by larskanis** [comment] 2022-01-10 08:26
@nevil Do you have a proposal for improving the line you mentioned? https://github.com/ffi/ffi/blob/master/ext/ffi_c/extconf.rb#L63

Is switching to `--enable-libffi-alloc` on all Macos architectures an option? I just remember that `--enable-libffi-alloc` has issues on Linux with PaX and in conjunction with `fork()`. That's why it's not the default there.

**Comment by nevil** [comment] 2022-01-11 04:39
@larskanis 
I've tried `bundle exec rake -- --enable-libffi-alloc' on the below:
Intel darwin20 (11.6.2/Big Sur) - Tests pass
Intel darwin21 (12.1/Monterey) - Tests pass
arm64 darwin21 (12.1/Monterey) - Tests pass

So I believe that from darwin20 and later it is fine to always use `--enable-libffi-alloc`.
(if the ffi tests are enough :-) )

And this from Apple's version of Ruby (the Big Sur 11.5 release is available)
```
# <rdar://problem/64900188> ruby needs to switch to using the modern libffi closure API as the legacy API is not supported on arm64
Extra_CC_Flags += -DUSE_FFI_CLOSURE_ALLOC
```

https://github.com/apple-oss-distributions/ruby/blob/ruby-145.100.1/Makefile#L19


So I guess extconf.rb could look for darwin20 and later and then always use `--enable-libffi-alloc`.

**Comment by mame** [comment] 2022-01-31 01:59
@larskanis I think the workaround should be `gem install ffi -- --enable-libffi-alloc`. (The additional `--` is needed.)

There have been many reports of ffi with M1 on Ruby's bug tracker. Can you update it so I can guide them to your comment?

**Comment by jonchoi** [comment] 2022-02-01 20:15
Thank you @mame ! It helped me move on to the next error lol
