### ISSUE TITLE
MacOS: error 'cputype does not match previous archive members' since ffi-1.9.21

### ISSUE THREAD

**Issue by davidqhogan** [ffi/ffi#605] opened 2018-02-06 12:38 UTC
Hi,

Today our project that depends on compass, that depends on ffi, stopped building. To workaround, I changed:

`gem install -i ./compass compass --version $COMPASS_VERSION`

to

`CFLAGS="--disable-asm-optimizations" gem install -i ./compass compass --version $COMPASS_VERSION`

Hope this helps.

**Comment by unimatrixZxero** [comment] 2018-02-06 12:49
Yes, thanks, it helped me. Installs now on Mac OS X 10.3.3 (17D47) (MBP 15" mid-2015 2.8 GHz i7)

**Comment by jeffblake** [comment] 2018-02-06 22:18
`brew install automake`

Worked for me.

**Comment by vinhboy** [comment] 2018-02-07 05:51
Confirm conflict on Mac 10.13.3

```
Running autoreconf for libffi
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
make: ***
```

@jeffblake's fix worked

**Comment by kusma** [comment] 2018-02-07 08:05
I'm seeing the same problem. The specific error I'm getting is:
```
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(ffi64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(unix64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(ffiw64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(win64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
libtool: link: ranlib .libs/libffi_convenience.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(ffi64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(unix64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(ffiw64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(win64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
make[3]: *** [libffi_convenience.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** ["/Library/Ruby/Gems/2.3.0/gems/ffi-1.9.21/ext/ffi_c"/libffi-i386/.libs/libffi_convenience.a] Error 2
```
So it seems the problem is mixing 32-bit and 64-bit object files in the same archive.

Passing `CFLAGS="--disable-asm-optimizations"` worked fine for me as well.

**Comment by larskanis** [comment] 2018-02-23 05:36
OK, just pushed ffi-1.9.22, which hopefully solves this issue. Could you please re-try?

**Comment by pmanrubia** [comment] 2018-02-23 09:35
@larskanis `ffi-1.9.22` worked for me. Thank you 👍

**Comment by larskanis** [comment] 2018-02-23 10:00
@pmanrubia Thanks for responding, but your issue was about "autoreconf: failed to run aclocal: No such file or directory"

Is the original issue resolved, what `CFLAGS="--disable-asm-optimizations"` is required or otherwise the following error ocures?
```
libtool: link: ar cru .libs/libffi_convenience.a src/.libs/prep_cif.o src/.libs/types.o src/.libs/raw_api.o src/.libs/java_raw_api.o src/.libs/closures.o src/x86/.libs/ffi64.o src/x86/.libs/unix64.o src/x86/.libs/ffiw64.o src/x86/.libs/win64.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive member: .libs/libffi_convenience.a(ffi64.o) cputype (16777223) does not match previous archive members cputype (7) (all members must match)
```

**Comment by kusma** [comment] 2018-02-23 10:11
@larskanis: Doesn't seem to be fixed; I still get cputype 16777223 mixed with cputype 7 with ffi-1.9.22 without `CFLAGS="--disable-asm-optimizations"`.

**Comment by pmanrubia** [comment] 2018-02-23 10:26
> @pmanrubia Thanks for responding, but your issue was about "autoreconf: failed to run aclocal: No such file or directory"

@larskanis: I didn't raise this issue. I just googled about the problem, got the same error, it was fixed with the upgrade, and gave feedback in case it helps others.

**Comment by pmanrubia** [comment] 2018-02-23 11:00
@larskanis I do apologise, I linked to the wrong issue. I have deleted my comment as they can cause trouble to other users.

**Comment by davidqhogan** [comment] 2018-02-23 16:29
Yes still broken here, please reopen this bug if the issue isn't being tracked elsewhere

**Comment by larskanis** [comment] 2018-02-23 17:12
Can someone post a full console output of gem install with this issue? My guess is that it's related to the [multi arch build on darwin](https://github.com/ffi/ffi/blob/master/ext/ffi_c/libffi.darwin.mk#L47). Unfortunately I can't reproduce this - I don't have a Mac.

**Comment by matteosecli** [comment] 2018-02-24 15:56
`CFLAGS="--disable-asm-optimizations" gem install  ffi -v '1.9.22'` works for me; it doesn't without the suggested CFLAGS. `gem install  ffi -v '1.9.18'`, instead, works without any issue.

I'm on a MBP 15" (2017) with an i7-7820HQ CPU.

Logs (`gem_make.out` and `mkmf.log`):
[ffi-1.9.22_logs.zip](https://github.com/ffi/ffi/files/1754576/ffi-1.9.22_logs.zip)

**Comment by larskanis** [comment] 2018-02-24 23:22
Could you please try
```
gem inst ffi --pre
```
I've got some hope that it solves this issue...

**Comment by matteosecli** [comment] 2018-02-25 00:02
> Could you please try
> ```
> gem inst ffi --pre
> ```

The above command works fine, I've just installed `ffi-1.9.23.pre1` without any issue!

**Comment by larskanis** [comment] 2018-02-25 07:09
@matteosecli Thanks for the confirmation! I just pushed final ffi-1.9.23 to rubygems.org. It should fix this issue, so that the workaround to use `CFLAGS="--disable-asm-optimizations"` isn't needed any longer.

**Closed by larskanis** 2018-02-25 07:09 UTC
