### ISSUE TITLE
Ubuntu 20.04 LTS issue with ffi gem : expects libffi6 to be installed whereas this distro contains libffi7

### ISSUE THREAD

**Issue by rabi-nsox** [ffi/ffi#773] opened 2020-05-04 18:18 UTC
Not including my complicated gemfile.lock, but it has this dependency on ffi
    sassc (2.2.1)
      ffi (~> 1.9)

On Ubuntu 20.04 it throws the following error:
	 1: from /home/xxx/apps/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/xxx/apps/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
	...
        ...
	 1: from /home/xxx/apps/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `block in require'
/home/xxx/apps/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require': libffi.so.6: cannot open shared object file: No such file or directory - /home/xxx/apps/shared/bundle/ruby/2.6.0/gems/ffi-1.12.2/lib/ffi_c.so (LoadError)

Workaround:
To get this to work I simply softlinked to  libffi.so.7 
$ dpkg-query -L libffi7
/usr/lib/x86_64-linux-gnu/libffi.so.7.1.0
sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6

My Environment:
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.8
  - RUBY VERSION: 2.6.6 (2020-03-31 patchlevel 146) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/xxx/.rvm/gems/ruby-2.6.6
  - USER INSTALLATION DIRECTORY: /home/xxx/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /home/xxx/.rvm/rubies/ruby-2.6.6/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/xxx/.rvm/gems/ruby-2.6.6/bin
  - SPEC CACHE DIRECTORY: /home/xxx/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/xxx/.rvm/rubies/ruby-2.6.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/xxx/.rvm/gems/ruby-2.6.6
     - /home/xxx/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/xxx/.rvm/gems/ruby-2.6.6/bin
     - /home/xxx/.rvm/gems/ruby-2.6.6@global/bin
     - /home/xxx/.rvm/rubies/ruby-2.6.6/bin
     - /home/xxx/.rvm/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin

ProblemType: Bug
ApportVersion: 2.20.11-0ubuntu27
Architecture: amd64
CasperMD5CheckResult: skip
Date: Mon May  4 19:29:39 2020
Dependencies:
 gcc-10-base 10-20200411-0ubuntu1
 libc6 2.31-0ubuntu9
 libcrypt1 1:4.4.10-10ubuntu4
 libgcc-s1 10-20200411-0ubuntu1
 libidn2-0 2.2.0-2
 libunistring2 0.9.10-2
DistroRelease: Ubuntu 20.04
Package: libffi7 3.3-4
PackageArchitecture: amd64
ProcCpuinfoMinimal:
 processor	: 5
 vendor_id	: GenuineIntel
 cpu family	: 6
 model		: 158
 model name	: Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
 stepping	: 10
 microcode	: 0xca
 cpu MHz		: 3906.271
 cache size	: 9216 KB
 physical id	: 0
 siblings	: 6
 core id		: 5
 cpu cores	: 6
 apicid		: 10
 initial apicid	: 10
 fpu		: yes
 fpu_exception	: yes
 cpuid level	: 22
 wp		: yes
 flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
 bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
 bogomips	: 6000.00
 clflush size	: 64
 cache_alignment	: 64
 address sizes	: 39 bits physical, 48 bits virtual
 power management:
ProcEnviron:
 TERM=xterm-256color
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/bin/bash
ProcVersionSignature: Ubuntu 5.4.0-28.32-generic 5.4.30
SourcePackage: libffi
Tags:  focal uec-images
Uname: Linux 5.4.0-28-generic x86_64
UpgradeStatus: Upgraded to focal on 2020-05-02 (1 days ago)
_MarkForUpload: True

**Comment by larskanis** [comment] 2020-05-04 19:09
Dupe of #769

**Closed by larskanis** 2020-05-04 19:09 UTC

**Comment by rabi-nsox** [comment] 2020-05-04 20:04
Your suggested solution did not work.
$ gem pristine ffi
Restoring gems to pristine condition...
Building native extensions. This could take a while...
Restored ffi-1.12.2
$ RAILS_ENV=production rails console
..
..
/home/pos/apps/shared/bundle/ruby/2.6.0/gems/activesupport-6.0.0/lib/active_support/dependencies.rb:325:in `require': cannot load such file -- 2.6/ffi_c (LoadError)

**Comment by MartinMcDermid** [comment] 2020-05-19 09:45
Still an issue for me after upgrade to 20.04.

**Comment by chaadow** [comment] 2020-06-22 13:24
@rabi-nsox @MartinMcDermid In my case I'm using multi build in docker. Having a build image, and a final image without the build tools

it so happens that my build image was "outdated" using libffi 6.0, so All I had to do is update that image to get the latest libffi 7. 
And then redeploy my application and it worked without the need to do any symbolic link maneuvering. Perhaps you have a similar setup
(At first I thought updating `sassc` would solve the issue but it turned out that was not the main issue.)

**Comment by ConorSheehan1** [comment] 2020-09-01 22:33
Seeing the same issue with:
Ubuntu 18.04.5 LTS
rbenv 1.1.1
ruby 2.7.1
ffi 1.13.1

**Comment by rabi-nsox** [comment] 2020-09-02 06:22
@ConorSheehan1  @MartinMcDermid, @chaadow 

I am not sure if @larskanis is  seeing this issue that has been closed.
You may be better of filing a new issue, to bring it to the notice of the FFI gem team.
Lars with multiple people running in the same issue, you clearly have a problem.

Rabi

**Comment by eregon** [comment] 2020-09-02 10:02
> Lars with multiple people running in the same issue, you clearly have a problem.

Maybe reread this? (it sounds bad). There might be a problem in FFI, but nothing is clear to me, it's easy to mess up your own development environment too (which was the cast of the first report).

@ConorSheehan1 We'll need more details and how to reproduce it.

**Comment by abdullah5514** [comment] 2020-09-26 15:06
Instaling required libffi on ubuntu fixed my issue. I was required to install libffi.so.7. So i install it from here:

[http://mirrors.edge.kernel.org/ubuntu/pool/main/libf/libffi/](url)

**Comment by luhova** [comment] 2020-11-02 10:50
running `gem pristine ffi` worked for me

**Comment by Lewiscowles1986** [comment] 2021-05-30 22:04
So gem pristine and bundle pristine did not work for me

* Ubuntu 18.04
* rvm
* brew

So I think what is happening is that linuxbrew dependencies are picked up by some parts of rvm, but not others.

Here was the process that worked for me in finding a fix:

* file $HOME/.rvm/gems/ruby-2.7.2/gems/ffi-1.15.1/lib/ffi_c.so
* ldd $HOME/.rvm/gems/ruby-2.7.2/gems/ffi-1.15.1/lib/ffi_c.so
  ```
  ...
  	libffi.so.7 => not found
  ...
  ```
* ln -s /home/linuxbrew/.linuxbrew/lib/libffi.so.7 $HOME/.rvm/rubies/ruby-2.7.2/lib/libffi.so.7
* ldd $HOME/.rvm/gems/ruby-2.7.2/gems/ffi-1.15.1/lib/ffi_c.so
  ```
  ...
  	libffi.so.7 => $HOME/.rvm/rubies/ruby-2.7.2/lib/libffi.so.7 (0x00007f321f341000)
  ...
  ``

**Comment by Envek** [comment] 2021-08-12 11:48
Same here: Ubuntu 18.04, rbenv, linuxbrew.

Workaround from @Lewiscowles1986 helped me:
```sh
ln -s /home/linuxbrew/.linuxbrew/lib/libffi.so.7 $HOME/.rbenv/versions/2.7.4/lib/libffi.so.7
```

**Comment by dorianmariefr** [comment] 2021-08-23 16:39
Getting the latest ffi from github worked for me, e.g.:

```
gem "ffi", github: "ffi/ffi"
```

in my `Gemfile`

**Comment by dorianmariefr** [comment] 2021-08-23 17:11
In my case, adding `gem "ffi"` to my `Gemfile` fixed it https://stackoverflow.com/q/65000467/12544391
