### ISSUE TITLE
invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass 

### ISSUE THREAD

**Issue by Karthikds** [ffi/ffi#452] opened 2015-08-10 08:05 UTC
I am trying to install selenium-webdriver/ watir webdriver gem. Its raise the following exception- 
"invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /cache/ffi-1.9.10.gem"

Also tried to install 1.9.9/1.0.9. I am facing the same issue.

**Comment by tduehr** [comment] 2015-08-14 22:24
What platform? What version of Ruby?

**Comment by Karthikds** [comment] 2015-08-19 10:44
Ruby 2.1.1p76
Platform: ubuntu 14.04

**Comment by tduehr** [comment] 2015-08-19 21:12
I cannot reproduce this. Both 14.04 and 15.04 running ruby 2.1.1 install just fine for me.

Try clearing the cached gem file before attempting to install again.

If that fails, I need to know how ruby was installed, where and what you're doing to install ffi.

**Comment by tduehr** [comment] 2015-10-19 14:18
no comment in two months, closing.

**Closed by tduehr** 2015-10-19 14:18 UTC
