### ISSUE TITLE
Update bundled libffi in order to support ppc64le

### ISSUE THREAD

**Issue by ruscur** [ffi/ffi#482] opened 2016-02-18 04:46 UTC
The very old version of libffi bundled with ffi does not know about the ppc64le architecture.  ffi can still be built if libffi is built separately, however installing the ffi gem by itself will fail on ppc64le.

libffi should be kept up to date, or entirely removed from ffi and expected to be installed separately.

**Comment by tduehr** [comment] 2016-02-18 20:53
duplicate of #466

**Closed by tduehr** 2016-02-18 20:53 UTC
