### ISSUE TITLE
native Apple Silicon (M1) compatible version of ffi

### ISSUE THREAD

**Issue by mesqueeb** [ffi/ffi#922] opened 2021-11-16 08:16 UTC
Are there any plans for this?

I'd rather keep my intel around and not install rosetta until `ffi` gets a native Apple Silicon (M1) version.

Would love to hear if there are any plans / development / schedule. : )

**Comment by mesqueeb** [comment] 2021-11-25 03:24
CC/ @larskanis

**Comment by mesqueeb** [comment] 2021-12-06 02:54
@larskanis @eregon is there any way I can sponsor the development of this feature request?

**Comment by ZsoltMolnarMBH** [comment] 2021-12-14 15:38
Please fix this bug. It is super annoying.

**Comment by headius** [comment] 2022-01-06 20:33
JRuby just merged in a final major piece for Apple M1 FFI support today... might be good enough for you until the C extension is updated.

https://twitter.com/headius/status/1479188425660149761

**Comment by larskanis** [comment] 2022-01-10 08:30
> Please fix this bug. It is super annoying.

Which bug shall be fixed? What is the error? Current ffi-1.15.4 should work well on Apple-M1. 

Does enabling libffi allocation as [described here](https://github.com/ffi/ffi/issues/800#issuecomment-1008308614) fix your issues?

**Comment by mesqueeb** [comment] 2022-01-10 08:39
I couldn't build with Capacitor anymore. 

Installing native M1 cocoapods Worked but trying to build the app with Capagitor failed because of an upstream ffi issue. 

Will replicate it and post the error here soon.

**Comment by eregon** [comment] 2022-01-10 10:26
Given it's cocoapods maybe it's the same error as https://github.com/typhoeus/ethon/issues/193
Tons of reports about that on the CRuby mailing list, but it's established by now it's not CRuby or FFI's fault for that bug.

**Comment by moekify** [comment] 2022-01-12 11:02
I am encountering a similar issue with capacitor.

It is fixable though by using a workaround rosetta, which might be useful for you @mesqueeb

```
sudo arch -x86_64 gem install ffi
cd ios/App
arch -x86_64 pod repo update
arch -x86_64 pod install
```

Relevant error Line:
```
[capacitor] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’: dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 0x0009): tried: ‘/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle’ (mach-o file, but is an incompatible architecture (have ‘arm64’, need ‘x86_64’)), ‘/usr/lib/ffi_c.bundle’ (no such file) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle (LoadError)
```

Full Error Log:
```
capacitor sync ios
 ionic:lib:telemetry Sending telemetry for command: ‘ionic capacitor run’ [
 ionic:lib:telemetry  ‘ios’,
 ionic:lib:telemetry  ‘--external’,
 ionic:lib:telemetry  ‘--livereload’,
 ionic:lib:telemetry  ‘--verbose’,
 ionic:lib:telemetry  ‘--interactive’,
 ionic:lib:telemetry  ‘--color’
 ionic:lib:telemetry ] +0ms
[capacitor]  Found 1 Cordova plugin for ios
[capacitor]   cordova-plugin-ionic (5.4.7)
[capacitor]  Found 0 Capacitor plugins for ios:
[capacitor]  Found 1 Cordova plugin for ios
[capacitor]   cordova-plugin-ionic (5.4.7)
[capacitor] [error] Analyzing dependencies
[capacitor] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’: dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 0x0009): tried: ‘/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle’ (mach-o file, but is an incompatible architecture (have ‘arm64’, need ‘x86_64’)), ‘/usr/lib/ffi_c.bundle’ (no such file) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle (LoadError)
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <top (required)>'
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:53:in `refresh_metadata’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:31:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:30:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `new’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:322:in `source_from_path’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `map’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:26:in `aggregate’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:60:in `all’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:77:in `stack’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:24:in `report’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
[capacitor]   from /usr/local/bin/pod:23:in `load’
[capacitor]   from /usr/local/bin/pod:23:in `<main>'
[capacitor] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’: cannot load such file -- 2.6/ffi_c (LoadError)
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:3:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:53:in `refresh_metadata’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:31:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:30:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `new’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:322:in `source_from_path’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `map’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:26:in `aggregate’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:60:in `all’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:173:in `repo_information’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:77:in `stack’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface/error_report.rb:24:in `report’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:66:in `report_error’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:396:in `handle_exception’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:337:in `rescue in run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:324:in `run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
[capacitor]   from /usr/local/bin/pod:23:in `load’
[capacitor]   from /usr/local/bin/pod:23:in `<main>'
[capacitor] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’: dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle, 0x0009): tried: ‘/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle’ (mach-o file, but is an incompatible architecture (have ‘arm64’, need ‘x86_64’)), ‘/usr/lib/ffi_c.bundle’ (no such file) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi_c.bundle (LoadError)
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:5:in `rescue in <top (required)>'
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:2:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:53:in `refresh_metadata’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:31:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:30:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `new’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:315:in `block in source_from_path’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:322:in `source_from_path’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `block in aggregate_with_repos’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `map’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:331:in `aggregate_with_repos’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:26:in `aggregate’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:60:in `all’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source/manager.rb:393:in `source_with_url’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/sources_manager.rb:22:in `find_or_create_source_with_url’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:178:in `block in sources’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:177:in `map’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:177:in `sources’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1077:in `block in resolve_dependencies’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:416:in `analyze’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/user_interface.rb:64:in `section’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:240:in `resolve_dependencies’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/installer.rb:161:in `install!'
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command/install.rb:52:in `run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/lib/cocoapods/command.rb:52:in `run’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.2/bin/pod:55:in `<top (required)>'
[capacitor]   from /usr/local/bin/pod:23:in `load’
[capacitor]   from /usr/local/bin/pod:23:in `<main>'
[capacitor] /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’: cannot load such file -- 2.6/ffi_c (LoadError)
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.4/lib/ffi.rb:3:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:53:in `refresh_metadata’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/source.rb:31:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.2/lib/cocoapods-core/cdn_source.rb:30:in `initialize’
[capacitor]   from /Library/Ruby/Gems/2.6.0/gems/cocoapods-core
```

**Comment by mesqueeb** [comment] 2022-01-13 00:24
@eregon  @moekify
I will double check to confirm if the error is the same, but I believe it is the same error. It clearly points to ffi... 😅 

This workaround shows (just as many SO posts) that we need to install `sudo arch -x86_64 gem install ffi` which is the whole thing I want to avoid.

I'm ok installing x86 apps, but when it comes to command line packages, I'd really rather not mess with 2 different architectures at the same time.

**Comment by headius** [comment] 2022-01-14 17:39
@larskanis I believe at minimum we need to fix #916. I attempted to run the FFI specs on M1 today and it appears that the ffi_c.bundle is *not* being built with combined x86_64 + arm64 support, which prevents an arm64 CRuby from loading it.

The failures look like this:

```
Failure/Error: require 'ffi_c'

LoadError:
  dlopen(/Users/administrator/projects/ffi/lib/ffi_c.bundle, 0x0009): missing compatible arch in /Users/administrator/projects/ffi/lib/ffi_c.bundle - /Users/administrator/projects/ffi/lib/ffi_c.bundle
# ./lib/ffi.rb:5:in `require'
# ./lib/ffi.rb:5:in `rescue in <top (required)>'
# ./lib/ffi.rb:2:in `<top (required)>'
# ./spec/ffi/fixtures/compile.rb:8:in `require'
# ./spec/ffi/fixtures/compile.rb:8:in `<top (required)>'
# ./spec/ffi/spec_helper.rb:6:in `require_relative'
# ./spec/ffi/spec_helper.rb:6:in `<top (required)>'
# ./spec/ffi/variadic_spec.rb:6:in `require'
# ./spec/ffi/variadic_spec.rb:6:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- 2.6/ffi_c
#   ./lib/ffi.rb:3:in `require'
```

I don't grok extconf so I wasn't sure how to fix it, but I'm pretty sure this is the root cause of most people's issues with FFI on CRuby on Darwin on Apple Silicon.

**Comment by JIAZHEN** [comment] 2022-01-15 22:41
Will this issue get fixed? Would be nice to work in native M1

**Comment by andesappal** [comment] 2022-01-24 15:15
Error running pod install and launching application on iPhone 13 (Apple M1) #97136

**Comment by monfresh** [comment] 2022-03-09 17:46
`ffi` works fine on Apple Silicon M1 with Ruby 2.7.x and 3.x. I've been using it without any issues for over a year on my M1, and without having to set any special flags or use Rosetta.

There is a lot of outdated advice out there, which causes people to mess up their development environment. Here are the three main reasons people are struggling to install `ffi` on their M1 Macs:

1) They don't have a proper Ruby development environment, and they're trying to install gems using the system Ruby.

2) They're trying to install an older version. If you're trying to install `ffi` as part of a Ruby project with a `Gemfile`, try running `bundle update ffi` to get the latest version.

3) They followed outdated advice to use `arch -x86_64` or run terminal in Rosetta mode, or worse, bad advice to use `sudo`.

So how can you get a proper Ruby development environment?

With [Ruby on Mac](https://www.rubyonmac.dev/?utm_source=ffi-922)! I built this automated script to help people like you get a proper Ruby setup. I guarantee it will fix your `ffi` and `cocoapods` issues or I will personally fix it for you.

Here's a review from someone who had `ffi` issues:

> You (and your wonderful script) saved me from great peril today. I had developed my first Jekyll site some months ago. And I am now in the middle of developing a site using Eleventy. Earlier today, I went back to my Jekyll site to make sure that I could still build it as I had some updates to make. Sadly, the site failed to build with the horrendous “ffi” error that is going around. After numerous ill-fated attempts to get it working, trying every workaround that I could find, I ultimately came across your script. While it does take some time to get through it, I have to say that it has worked wonderfully! My site builds once again and I feel like the ruby platform that your script placed on my system is far less fragile than before. Thank you again for the great script and your service to the community.

**Comment by eregon** [comment] 2022-03-09 18:04
Let's close this as it has been addressed in recent FFI release.

The comment above is a good summary of common issues.
In my understanding the main issue is the system ruby on macOS has two architectures but Ruby/RubyGems don't really support that and also that system ruby reports confusing values in RbConfig for the arch, leading to endless problems.
Building your own Ruby which just the darwin-aarch64 architecture solves that.

**Closed by eregon** 2022-03-09 18:04 UTC

**Comment by JCTD** [comment] 2022-04-07 14:00
@monfresh what about an older version of ffi? ffi v 1.9.18 with ruby 2.3.6. I get an error trying to install that version of ffi on an M1.

**Comment by monfresh** [comment] 2022-04-07 20:30
@JCTD Can you tell me more about what's preventing you from updating to the latest ffi? Feel free to [email me](https://www.rubyonmac.dev/faq/#you-have-another-question) if you prefer.

Ruby 2.3.6 is a super old version and should not be used in production. I recommend upgrading your project to at least 2.7.5. On M1, the oldest version of Ruby you can safely install without using Rosetta is 2.6.8. 

If you need help updating your project, that's a service I provide.

**Comment by TechFounder** [comment] 2022-04-14 22:32
Thanks @monfresh, at first I thought that we wouldn't be able to upgrade it due to the fact that we didn't want to upgrade other dependencies. But we found a way.

**Comment by jgfntu** [comment] 2022-05-16 14:21
> `ffi` works fine on Apple Silicon M1 with Ruby 2.7.x and 3.x. I've been using it without any issues for over a year on my M1, and without having to set any special flags or use Rosetta.
> 
> There is a lot of outdated advice out there, which causes people to mess up their development environment. Here are the three main reasons people are struggling to install `ffi` on their M1 Macs:
> 
> 1. They don't have a proper Ruby development environment, and they're trying to install gems using the system Ruby.
> 2. They're trying to install an older version. If you're trying to install `ffi` as part of a Ruby project with a `Gemfile`, try running `bundle update ffi` to get the latest version.
> 3. They followed outdated advice to use `arch -x86_64` or run terminal in Rosetta mode, or worse, bad advice to use `sudo`.
> 
> So how can you get a proper Ruby development environment?
> 
> With [Ruby on Mac](https://www.rubyonmac.dev/?utm_source=ffi-922)! I built this automated script to help people like you get a proper Ruby setup. I guarantee it will fix your `ffi` and `cocoapods` issues or I will personally fix it for you.
> 
> Here's a review from someone who had `ffi` issues:
> 
> > You (and your wonderful script) saved me from great peril today. I had developed my first Jekyll site some months ago. And I am now in the middle of developing a site using Eleventy. Earlier today, I went back to my Jekyll site to make sure that I could still build it as I had some updates to make. Sadly, the site failed to build with the horrendous “ffi” error that is going around. After numerous ill-fated attempts to get it working, trying every workaround that I could find, I ultimately came across your script. While it does take some time to get through it, I have to say that it has worked wonderfully! My site builds once again and I feel like the ruby platform that your script placed on my system is far less fragile than before. Thank you again for the great script and your service to the community.

it works for me, thx
